spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: fsd-account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:33060/fsd_account?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: fsd_account_admin
    password: zaq12wsx
  jpa:
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
server:
  servlet:
    context-path: /account
  port: 9001
  
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:8081/eureka
  instance:
    prefer-ip-address: true
    ipAddress: 172.17.0.1
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true
logging:
  config: classpath:logback-boot_dev.xml
 
---
spring:
  profiles: k8s
  application:
    name: fsd-account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33060/fsd_account?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: fsd_account_admin
    password: zaq12wsx
          
server:
  servlet:
    context-path: /account
  port: 9001
  
eureka:
  client:
    service-url:
      defaultZone: http://fsd-registry:8081/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true

